/* Gerado por scripts/showcase/build.js — não editar à mão. */
window.__SHOWCASE = {
  "generatedAt": "2026-07-15T19:23:20.558Z",
  "updatedLabel": "julho de 2026",
  "totals": {
    "screens": 20,
    "shots": 55,
    "modules": 6
  },
  "modules": [
    {
      "title": "Autenticação",
      "description": "Fluxo de entrada, criação de conta e recuperação de acesso.",
      "screens": 3,
      "shots": 8
    },
    {
      "title": "Home",
      "description": "Painel com saldo, evolução das comissões e últimas indicações.",
      "screens": 1,
      "shots": 3
    },
    {
      "title": "Indicar",
      "description": "Links de indicação, histórico de indicados e rede formada.",
      "screens": 5,
      "shots": 12
    },
    {
      "title": "Comissões",
      "description": "Ganhos, saldos e solicitação de saque com Nota Fiscal.",
      "screens": 3,
      "shots": 9
    },
    {
      "title": "Conta",
      "description": "Dados pessoais, bancários, segurança e preferências.",
      "screens": 5,
      "shots": 11
    },
    {
      "title": "Suporte",
      "description": "Central de ajuda, contato e acompanhamento de solicitações.",
      "screens": 3,
      "shots": 12
    }
  ],
  "shots": [
    {
      "id": "login-v1",
      "index": 1,
      "label": "Acesso do afiliado",
      "desc": "Entrada com e-mail, senha, lembrar-me e recuperação de acesso.",
      "module": "Autenticação",
      "screenId": "login",
      "screenTitle": "Tela de Login",
      "route": "AffiliateLogin",
      "image": "assets/screens/01-login-v1.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "login-v2",
      "index": 2,
      "label": "Erro de credenciais",
      "desc": "Feedback quando o e-mail ou a senha não conferem.",
      "module": "Autenticação",
      "screenId": "login",
      "screenTitle": "Tela de Login",
      "route": "AffiliateLogin",
      "image": "assets/screens/02-login-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "register-v1",
      "index": 3,
      "label": "Pessoa Física",
      "desc": "Cadastro com CPF, contatos e os dois aceites obrigatórios.",
      "module": "Autenticação",
      "screenId": "register",
      "screenTitle": "Tela de Cadastro",
      "route": "AffiliateRegister",
      "image": "assets/screens/03-register-v1.png",
      "fullImage": "assets/screens/03-register-v1-full.png",
      "exists": true
    },
    {
      "id": "register-v2",
      "index": 4,
      "label": "Pessoa Jurídica",
      "desc": "Variação com razão social e CNPJ.",
      "module": "Autenticação",
      "screenId": "register",
      "screenTitle": "Tela de Cadastro",
      "route": "AffiliateRegister",
      "image": "assets/screens/04-register-v2.png",
      "fullImage": "assets/screens/04-register-v2-full.png",
      "exists": true
    },
    {
      "id": "register-v3",
      "index": 5,
      "label": "Validação dos campos",
      "desc": "Erros exibidos abaixo de cada campo obrigatório.",
      "module": "Autenticação",
      "screenId": "register",
      "screenTitle": "Tela de Cadastro",
      "route": "AffiliateRegister",
      "image": "assets/screens/05-register-v3.png",
      "fullImage": "assets/screens/05-register-v3-full.png",
      "exists": true
    },
    {
      "id": "register-v4",
      "index": 6,
      "label": "Cadastro preenchido",
      "desc": "Formulário completo com CPF e telefone mascarados.",
      "module": "Autenticação",
      "screenId": "register",
      "screenTitle": "Tela de Cadastro",
      "route": "AffiliateRegister",
      "image": "assets/screens/06-register-v4.png",
      "fullImage": "assets/screens/06-register-v4-full.png",
      "exists": true
    },
    {
      "id": "forgot-v1",
      "index": 7,
      "label": "Informar e-mail",
      "desc": "Envio do link de recuperação para o e-mail cadastrado.",
      "module": "Autenticação",
      "screenId": "forgot",
      "screenTitle": "Recuperação de Senha",
      "route": "AffiliateForgotPassword",
      "image": "assets/screens/07-forgot-v1.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "forgot-v2",
      "index": 8,
      "label": "Link enviado",
      "desc": "Confirmação com instrução para verificar a caixa de entrada.",
      "module": "Autenticação",
      "screenId": "forgot",
      "screenTitle": "Recuperação de Senha",
      "route": "AffiliateForgotPassword",
      "image": "assets/screens/08-forgot-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "dashboard-v1",
      "index": 9,
      "label": "Visão geral",
      "desc": "Saudação, métricas, saldo disponível e pendente.",
      "module": "Home",
      "screenId": "dashboard",
      "screenTitle": "Dashboard",
      "route": "AffiliateDashboard",
      "image": "assets/screens/09-dashboard-v1.png",
      "fullImage": "assets/screens/09-dashboard-v1-full.png",
      "exists": true
    },
    {
      "id": "dashboard-v2",
      "index": 10,
      "label": "Evolução e link principal",
      "desc": "Gráfico dos últimos 6 meses e ações do link de indicação.",
      "module": "Home",
      "screenId": "dashboard",
      "screenTitle": "Dashboard",
      "route": "AffiliateDashboard",
      "image": "assets/screens/10-dashboard-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "dashboard-v3",
      "index": 11,
      "label": "Últimas indicações",
      "desc": "As três indicações mais recentes com status e valor.",
      "module": "Home",
      "screenId": "dashboard",
      "screenTitle": "Dashboard",
      "route": "AffiliateDashboard",
      "image": "assets/screens/11-dashboard-v3.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "links-v1",
      "index": 12,
      "label": "Links de indicação",
      "desc": "Criação de link e lista com cliques, cadastros e status.",
      "module": "Indicar",
      "screenId": "links",
      "screenTitle": "Meus Links",
      "route": "AffiliateMyLinks",
      "image": "assets/screens/12-links-v1.png",
      "fullImage": "assets/screens/12-links-v1-full.png",
      "exists": true
    },
    {
      "id": "links-v2",
      "index": 13,
      "label": "Novo link preenchido",
      "desc": "Campo com o nome da campanha, pronto para gerar.",
      "module": "Indicar",
      "screenId": "links",
      "screenTitle": "Meus Links",
      "route": "AffiliateMyLinks",
      "image": "assets/screens/13-links-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "links-v3",
      "index": 14,
      "label": "Ações do link",
      "desc": "Menu com copiar, compartilhar, editar e desativar.",
      "module": "Indicar",
      "screenId": "links",
      "screenTitle": "Meus Links",
      "route": "AffiliateMyLinks",
      "image": "assets/screens/14-links-v3.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "links-v4",
      "index": 15,
      "label": "Confirmar desativação",
      "desc": "Diálogo antes de tirar um link do ar.",
      "module": "Indicar",
      "screenId": "links",
      "screenTitle": "Meus Links",
      "route": "AffiliateMyLinks",
      "image": "assets/screens/15-links-v4.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "historico-v1",
      "index": 16,
      "label": "Todas as indicações",
      "desc": "Resumo, busca, filtros por status e período.",
      "module": "Indicar",
      "screenId": "historico",
      "screenTitle": "Histórico de Indicações",
      "route": "AffiliateReferralHistory",
      "image": "assets/screens/16-historico-v1.png",
      "fullImage": "assets/screens/16-historico-v1-full.png",
      "exists": true
    },
    {
      "id": "historico-v2",
      "index": 17,
      "label": "Filtro Aprovadas",
      "desc": "Somente indicações já validadas pelo Empreitei.",
      "module": "Indicar",
      "screenId": "historico",
      "screenTitle": "Histórico de Indicações",
      "route": "AffiliateReferralHistory",
      "image": "assets/screens/17-historico-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "historico-v3",
      "index": 18,
      "label": "Busca sem resultado",
      "desc": "Estado vazio com atalho para limpar os filtros.",
      "module": "Indicar",
      "screenId": "historico",
      "screenTitle": "Histórico de Indicações",
      "route": "AffiliateReferralHistory",
      "image": "assets/screens/18-historico-v3.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "indicacao-v1",
      "index": 19,
      "label": "Indicação aprovada",
      "desc": "Dados do indicado, origem, comissão e linha do tempo.",
      "module": "Indicar",
      "screenId": "indicacao",
      "screenTitle": "Detalhe da Indicação",
      "route": "AffiliateReferralDetail",
      "image": "assets/screens/19-indicacao-v1.png",
      "fullImage": "assets/screens/19-indicacao-v1-full.png",
      "exists": true
    },
    {
      "id": "indicacao-v2",
      "index": 20,
      "label": "Indicação rejeitada",
      "desc": "Motivo da rejeição informado ao afiliado.",
      "module": "Indicar",
      "screenId": "indicacao",
      "screenTitle": "Detalhe da Indicação",
      "route": "AffiliateReferralDetail",
      "image": "assets/screens/20-indicacao-v2.png",
      "fullImage": "assets/screens/20-indicacao-v2-full.png",
      "exists": true
    },
    {
      "id": "rede-v1",
      "index": 21,
      "label": "Rede de indicados",
      "desc": "Total, ativos e taxa de ativação da rede.",
      "module": "Indicar",
      "screenId": "rede",
      "screenTitle": "Minha Rede",
      "route": "AffiliateNetwork",
      "image": "assets/screens/21-rede-v1.png",
      "fullImage": "assets/screens/21-rede-v1-full.png",
      "exists": true
    },
    {
      "id": "rede-v2",
      "index": 22,
      "label": "Filtro Prestadores",
      "desc": "Apenas prestadores cadastrados pelos seus links.",
      "module": "Indicar",
      "screenId": "rede",
      "screenTitle": "Minha Rede",
      "route": "AffiliateNetwork",
      "image": "assets/screens/22-rede-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "indicado-v1",
      "index": 23,
      "label": "Perfil do indicado",
      "desc": "Atividade, transações válidas e comissões relacionadas.",
      "module": "Indicar",
      "screenId": "indicado",
      "screenTitle": "Detalhe do Indicado",
      "route": "AffiliateNetworkMember",
      "image": "assets/screens/23-indicado-v1.png",
      "fullImage": "assets/screens/23-indicado-v1-full.png",
      "exists": true
    },
    {
      "id": "comissoes-v1",
      "index": 24,
      "label": "Saldo e métricas",
      "desc": "Saldo disponível, pendente, acumulado e já sacado.",
      "module": "Comissões",
      "screenId": "comissoes",
      "screenTitle": "Minhas Comissões",
      "route": "AffiliateCommissions",
      "image": "assets/screens/24-comissoes-v1.png",
      "fullImage": "assets/screens/24-comissoes-v1-full.png",
      "exists": true
    },
    {
      "id": "comissoes-v2",
      "index": 25,
      "label": "Filtro Liberadas",
      "desc": "Somente comissões prontas para saque.",
      "module": "Comissões",
      "screenId": "comissoes",
      "screenTitle": "Minhas Comissões",
      "route": "AffiliateCommissions",
      "image": "assets/screens/25-comissoes-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "comissoes-v3",
      "index": 26,
      "label": "Filtro Canceladas",
      "desc": "Comissão cancelada, com valor riscado.",
      "module": "Comissões",
      "screenId": "comissoes",
      "screenTitle": "Minhas Comissões",
      "route": "AffiliateCommissions",
      "image": "assets/screens/26-comissoes-v3.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "comissao-v1",
      "index": 27,
      "label": "Comissão liberada",
      "desc": "Valor bruto, descontos, líquido e acompanhamento.",
      "module": "Comissões",
      "screenId": "comissao",
      "screenTitle": "Detalhe da Comissão",
      "route": "AffiliateCommissionDetail",
      "image": "assets/screens/27-comissao-v1.png",
      "fullImage": "assets/screens/27-comissao-v1-full.png",
      "exists": true
    },
    {
      "id": "saque-v1",
      "index": 28,
      "label": "Formulário",
      "desc": "Saldo, valor, conta de destino e Nota Fiscal.",
      "module": "Comissões",
      "screenId": "saque",
      "screenTitle": "Solicitar Saque",
      "route": "AffiliateWithdraw",
      "image": "assets/screens/28-saque-v1.png",
      "fullImage": "assets/screens/28-saque-v1-full.png",
      "exists": true
    },
    {
      "id": "saque-v2",
      "index": 29,
      "label": "Valor preenchido",
      "desc": "Saldo total aplicado e saldo restante calculado.",
      "module": "Comissões",
      "screenId": "saque",
      "screenTitle": "Solicitar Saque",
      "route": "AffiliateWithdraw",
      "image": "assets/screens/29-saque-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "saque-v3",
      "index": 30,
      "label": "Valor abaixo do mínimo",
      "desc": "Bloqueio quando o valor não atinge R$ 100,00.",
      "module": "Comissões",
      "screenId": "saque",
      "screenTitle": "Solicitar Saque",
      "route": "AffiliateWithdraw",
      "image": "assets/screens/30-saque-v3.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "saque-v4",
      "index": 31,
      "label": "Saldo insuficiente",
      "desc": "Bloqueio quando o valor excede o saldo disponível.",
      "module": "Comissões",
      "screenId": "saque",
      "screenTitle": "Solicitar Saque",
      "route": "AffiliateWithdraw",
      "image": "assets/screens/31-saque-v4.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "saque-v5",
      "index": 32,
      "label": "Nota Fiscal obrigatória",
      "desc": "Revisão bloqueada enquanto a NF não é anexada.",
      "module": "Comissões",
      "screenId": "saque",
      "screenTitle": "Solicitar Saque",
      "route": "AffiliateWithdraw",
      "image": "assets/screens/32-saque-v5.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "conta-v1",
      "index": 33,
      "label": "Identidade e menu",
      "desc": "Hero com avatar, status da conta e grupos de opções.",
      "module": "Conta",
      "screenId": "conta",
      "screenTitle": "Minha Conta",
      "route": "AffiliateAccount",
      "image": "assets/screens/33-conta-v1.png",
      "fullImage": "assets/screens/33-conta-v1-full.png",
      "exists": true
    },
    {
      "id": "conta-v2",
      "index": 34,
      "label": "Confirmar saída",
      "desc": "Diálogo de logout em duas etapas.",
      "module": "Conta",
      "screenId": "conta",
      "screenTitle": "Minha Conta",
      "route": "AffiliateAccount",
      "image": "assets/screens/34-conta-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "dados-v1",
      "index": 35,
      "label": "Dados pessoais",
      "desc": "Foto, contatos e informações somente leitura da conta.",
      "module": "Conta",
      "screenId": "dados",
      "screenTitle": "Meus Dados",
      "route": "AffiliatePersonalData",
      "image": "assets/screens/35-dados-v1.png",
      "fullImage": "assets/screens/35-dados-v1-full.png",
      "exists": true
    },
    {
      "id": "dados-v2",
      "index": 36,
      "label": "Alterar foto",
      "desc": "Opções de câmera, galeria e remoção.",
      "module": "Conta",
      "screenId": "dados",
      "screenTitle": "Meus Dados",
      "route": "AffiliatePersonalData",
      "image": "assets/screens/36-dados-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "dados-v3",
      "index": 37,
      "label": "Validação",
      "desc": "Erro ao tentar salvar sem o nome completo.",
      "module": "Conta",
      "screenId": "dados",
      "screenTitle": "Meus Dados",
      "route": "AffiliatePersonalData",
      "image": "assets/screens/37-dados-v3.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "bancarios-v1",
      "index": 38,
      "label": "Conta cadastrada",
      "desc": "Dados mascarados e aviso sobre a titularidade.",
      "module": "Conta",
      "screenId": "bancarios",
      "screenTitle": "Dados Bancários",
      "route": "AffiliateBankData",
      "image": "assets/screens/38-bancarios-v1.png",
      "fullImage": "assets/screens/38-bancarios-v1-full.png",
      "exists": true
    },
    {
      "id": "bancarios-v2",
      "index": 39,
      "label": "Edição",
      "desc": "Forma de recebimento, conta e titular com máscaras.",
      "module": "Conta",
      "screenId": "bancarios",
      "screenTitle": "Dados Bancários",
      "route": "AffiliateBankData",
      "image": "assets/screens/39-bancarios-v2.png",
      "fullImage": "assets/screens/39-bancarios-v2-full.png",
      "exists": true
    },
    {
      "id": "senha-v1",
      "index": 40,
      "label": "Formulário",
      "desc": "Senha atual, nova senha e confirmação.",
      "module": "Conta",
      "screenId": "senha",
      "screenTitle": "Alterar Senha",
      "route": "AffiliateChangePassword",
      "image": "assets/screens/40-senha-v1.png",
      "fullImage": "assets/screens/40-senha-v1-full.png",
      "exists": true
    },
    {
      "id": "senha-v2",
      "index": 41,
      "label": "Força da senha",
      "desc": "Barras e checklist das regras exigidas.",
      "module": "Conta",
      "screenId": "senha",
      "screenTitle": "Alterar Senha",
      "route": "AffiliateChangePassword",
      "image": "assets/screens/41-senha-v2.png",
      "fullImage": "assets/screens/41-senha-v2-full.png",
      "exists": true
    },
    {
      "id": "notificacoes-v1",
      "index": 42,
      "label": "Preferências ativas",
      "desc": "Switch mestre e avisos por grupo.",
      "module": "Conta",
      "screenId": "notificacoes",
      "screenTitle": "Notificações",
      "route": "AffiliateNotifications",
      "image": "assets/screens/42-notificacoes-v1.png",
      "fullImage": "assets/screens/42-notificacoes-v1-full.png",
      "exists": true
    },
    {
      "id": "notificacoes-v2",
      "index": 43,
      "label": "Notificações desativadas",
      "desc": "Aviso e controles desabilitados.",
      "module": "Conta",
      "screenId": "notificacoes",
      "screenTitle": "Notificações",
      "route": "AffiliateNotifications",
      "image": "assets/screens/43-notificacoes-v2.png",
      "fullImage": "assets/screens/43-notificacoes-v2-full.png",
      "exists": true
    },
    {
      "id": "ajuda-v1",
      "index": 44,
      "label": "Central de ajuda",
      "desc": "Busca, categorias e perguntas frequentes.",
      "module": "Suporte",
      "screenId": "ajuda",
      "screenTitle": "Ajuda e FAQ",
      "route": "AffiliateHelp",
      "image": "assets/screens/44-ajuda-v1.png",
      "fullImage": "assets/screens/44-ajuda-v1-full.png",
      "exists": true
    },
    {
      "id": "ajuda-v2",
      "index": 45,
      "label": "Pergunta expandida",
      "desc": "Resposta aberta no acordeão.",
      "module": "Suporte",
      "screenId": "ajuda",
      "screenTitle": "Ajuda e FAQ",
      "route": "AffiliateHelp",
      "image": "assets/screens/45-ajuda-v2.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "ajuda-v3",
      "index": 46,
      "label": "Busca no FAQ",
      "desc": "Resultados filtrados em tempo real.",
      "module": "Suporte",
      "screenId": "ajuda",
      "screenTitle": "Ajuda e FAQ",
      "route": "AffiliateHelp",
      "image": "assets/screens/46-ajuda-v3.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "ajuda-v4",
      "index": 47,
      "label": "Sem resultados",
      "desc": "Estado vazio com atalho para o suporte.",
      "module": "Suporte",
      "screenId": "ajuda",
      "screenTitle": "Ajuda e FAQ",
      "route": "AffiliateHelp",
      "image": "assets/screens/47-ajuda-v4.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "contato-v1",
      "index": 48,
      "label": "Formulário",
      "desc": "Categoria, assunto, descrição e anexo.",
      "module": "Suporte",
      "screenId": "contato",
      "screenTitle": "Fale Conosco",
      "route": "AffiliateContact",
      "image": "assets/screens/48-contato-v1.png",
      "fullImage": "assets/screens/48-contato-v1-full.png",
      "exists": true
    },
    {
      "id": "contato-v2",
      "index": 49,
      "label": "Validação",
      "desc": "Erros nos campos obrigatórios.",
      "module": "Suporte",
      "screenId": "contato",
      "screenTitle": "Fale Conosco",
      "route": "AffiliateContact",
      "image": "assets/screens/49-contato-v2.png",
      "fullImage": "assets/screens/49-contato-v2-full.png",
      "exists": true
    },
    {
      "id": "contato-v3",
      "index": 50,
      "label": "Formulário preenchido",
      "desc": "Categoria escolhida e contadores de caracteres.",
      "module": "Suporte",
      "screenId": "contato",
      "screenTitle": "Fale Conosco",
      "route": "AffiliateContact",
      "image": "assets/screens/50-contato-v3.png",
      "fullImage": "assets/screens/50-contato-v3-full.png",
      "exists": true
    },
    {
      "id": "contato-v4",
      "index": 51,
      "label": "Anexar arquivo",
      "desc": "Opções de foto, galeria e documento.",
      "module": "Suporte",
      "screenId": "contato",
      "screenTitle": "Fale Conosco",
      "route": "AffiliateContact",
      "image": "assets/screens/51-contato-v4.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "contato-v5",
      "index": 52,
      "label": "Minhas solicitações",
      "desc": "Histórico com protocolo, status e resposta.",
      "module": "Suporte",
      "screenId": "contato",
      "screenTitle": "Fale Conosco",
      "route": "AffiliateContact",
      "image": "assets/screens/52-contato-v5.png",
      "fullImage": null,
      "exists": true
    },
    {
      "id": "solicitacao-v1",
      "index": 53,
      "label": "Respondida",
      "desc": "Mensagem enviada e resposta da equipe.",
      "module": "Suporte",
      "screenId": "solicitacao",
      "screenTitle": "Detalhe da Solicitação",
      "route": "AffiliateSupportRequestDetail",
      "image": "assets/screens/53-solicitacao-v1.png",
      "fullImage": "assets/screens/53-solicitacao-v1-full.png",
      "exists": true
    },
    {
      "id": "solicitacao-v2",
      "index": 54,
      "label": "Aberta",
      "desc": "Solicitação ainda na fila de atendimento.",
      "module": "Suporte",
      "screenId": "solicitacao",
      "screenTitle": "Detalhe da Solicitação",
      "route": "AffiliateSupportRequestDetail",
      "image": "assets/screens/54-solicitacao-v2.png",
      "fullImage": "assets/screens/54-solicitacao-v2-full.png",
      "exists": true
    },
    {
      "id": "solicitacao-v3",
      "index": 55,
      "label": "Envio concluído",
      "desc": "Confirmação com o protocolo gerado.",
      "module": "Suporte",
      "screenId": "solicitacao",
      "screenTitle": "Detalhe da Solicitação",
      "route": "AffiliateSupportRequestDetail",
      "image": "assets/screens/55-solicitacao-v3.png",
      "fullImage": "assets/screens/55-solicitacao-v3-full.png",
      "exists": true
    }
  ]
};
